baseURL = "https://renatovassallo.github.io/"
languageCode = "en-us"
title = "Renato Vassallo"
theme = "PaperMod"

[params]
  math = true
  env = "production"
  ShowReadingTime = true

  [params.profileMode]
  enabled = true
  title = "Renato Vassallo"
  subtitle = """I am an economist at the Institute for Economic Analysis (IAE-CSIC) and an MRes student in the International Doctorate in Economic Analysis (IDEA) program. My work uses econometrics and machine learning to study economic dynamics and inform policy discussions."""
    imageUrl = "images/photo_bse.png"  # relative to /static
    imageTitle = "Renato Vassallo"
    imageWidth = 150

    [[params.profileMode.buttons]]
      name = "GitHub"
      url = "https://github.com/renatovassallo"
      icon = "github"

    [[params.profileMode.buttons]]
      name = "LinkedIn"
      url = "https://linkedin.com/in/renatovassallo"
      icon = "linkedin"


[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/home/"
    weight = 1

  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research/"
    weight = 2

  [[menu.main]]
    name = "CV"
    url = "pdf/cv_feb26.pdf"
    weight = 3

  [[menu.main]]
    name = "Software"
    url = "/software/"
    weight = 4

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 5
