baseURL = "https://renatovassallo.github.io/"
languageCode = "en-us"
title = "Renato Vassallo"
theme = "PaperMod"

[params]
  math = true
  env = "production"
  ShowReadingTime = true

  [params.profileMode]
  enabled = true
  title = "Renato Vassallo"
  subtitle = """Iâ€™m an economist and data scientist at the Institute for Economic Analysis (IAE-CSIC), working at the intersection of AI and economics. My research combines machine learning, natural language processing, and causal inference to build data-driven tools for economic insight and policy design."""
    imageUrl = "images/photo_bse.png"  # relative to /static
    imageTitle = "Renato Vassallo"
    imageWidth = 150

    [[params.profileMode.buttons]]
      name = "GitHub"
      url = "https://github.com/renatovassallo"
      icon = "github"

    [[params.profileMode.buttons]]
      name = "LinkedIn"
      url = "https://linkedin.com/in/renatovassallo"
      icon = "linkedin"


[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/home/"
    weight = 1

  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research/"
    weight = 2

  [[menu.main]]
    name = "CV"
    url = "pdf/cv_aug25.pdf"
    weight = 3

  [[menu.main]]
    name = "Software"
    url = "/software/"
    weight = 4

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 5
